package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Balcao extends VerticalLayout {
    protected VerticalLayout panelTD;
    protected Button btnNovoCalculoTD;
    protected Button btnNovaPrenotacaoTD;
    protected Button btnRegistroTDLote;
    protected Button btnNovaCertidaoTD;
    protected VerticalLayout panelPJ;
    protected Button btnNovoCalculoPJ;
    protected Button btnNovaPrenotacaoPJ;
    protected Button btnNovaCertidaoPJ;

    public Balcao() {
		Design.read(this);
	}
}
