package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.ComboBox;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BuscarPedidos extends VerticalLayout {
    protected HorizontalLayout panelBusca;
    protected ComboBox<br.com.exmart.rtdpjlite.vo.balcaoonline.PedidoMensagemTipo> comboPeditoMensagemTipo;
    protected TextField busca;
    protected Button btnFiltrarData;
    protected HorizontalLayout filtroData;
    protected DateField dtInicial;
    protected DateField dtFinal;
    protected Grid<br.com.exmart.rtdpjlite.model.portal.Pedido> gridBusca;
    protected Button btnPrenotarTD;
    protected Button btnPrenotarPJ;

    public BuscarPedidos() {
		Design.read(this);
	}
}
