package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.ComboBox;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BuscarIndicadores extends VerticalLayout {
    protected HorizontalLayout panelBusca;
    protected ComboBox<String> tipoIndicador;
    protected HorizontalLayout buscaPessoal;
    protected TextField txtBuscaPessoal;
    protected Button btnBuscarIndicadorPessoal;
    protected Button btnFiltrarData;
    protected HorizontalLayout buscaReal;
    protected ComboBox<String> comboObjeto;
    protected ComboBox<String> comboAtributo;
    protected TextField txtBuscaReal;
    protected Button btnBuscarIndicadorReal;
    protected HorizontalLayout filtroData;
    protected DateField dtInicial;
    protected DateField dtFinal;
    protected VerticalLayout resultado;

    public BuscarIndicadores() {
		Design.read(this);
	}
}
