package br.com.exmart.indicadorRTDPJ.ui;

import br.com.exmart.indicadorRTDPJ.ui.component.GridProtocolo;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.CssLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BuscarProtocolos extends VerticalLayout {
    protected VerticalLayout panelLine;
    protected HorizontalLayout panelBusca;
    protected ComboBox<String> tipoProtocolo;
    protected TextField busca;
    protected Button btnFiltrarData;
    protected Button btnFiltros;
    protected CssLayout panelFiltros;
    protected HorizontalLayout panelSwitch;
    protected RadioButtonGroup<String> switchTDPJ;
    protected HorizontalLayout filtroTipoProtocolo;
    protected HorizontalLayout filtroNatureza;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Natureza> comboNatureza;
    protected ComboBox<String> comboData;
    protected HorizontalLayout filtroData;
    protected DateField dtInicial;
    protected DateField dtFinal;
    protected HorizontalLayout filtroStatus;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Status> comboAndamento;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cliente> comboCliente;
    protected GridProtocolo gridProtocolo;

    public BuscarProtocolos() {
		Design.read(this);
	}
}
