package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CadastroCartorioParceiro extends VerticalLayout {
    protected ComboBox<br.com.exmart.rtdpjlite.model.Estado> estado;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cidade> cidade;
    protected TextField comarca;
    protected TextField cns;
    protected TextField cnpj;
    protected TextField denominacao;
    protected TextField apelido;
    protected TextField oficial;
    protected TextField cpf;
    protected TextField email;
    protected CheckBox icCertidaoEletronica;
    protected TextField qtdViasFisica;
    protected Button fechar;
    protected Button salvar;

    public CadastroCartorioParceiro() {
        Design.read(this);
    }
}
