package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CardParte extends VerticalLayout {
    protected VerticalLayout panelBasico;
    protected Label labelNome;
    protected Label labelDocumento;
    protected Label labelIdentidade;
    protected Label labelQualificacao;
    protected Label labelVlParticipacao;
    protected Label labelVlCotas;
    protected VerticalLayout panelDetalhes;
    protected Label labelEmail;
    protected Label labelTelefone;
    protected Label labelNacionalidade;
    protected Label labelEstadoCivil;
    protected Label labelProfissao;
    protected Label labelEndereco;
    protected Label labelEnderecoNumero;
    protected Label labelCep;
    protected Label labelComplemento;
    protected Label labelBairro;
    protected Label labelCidade;
    protected Label labelEstado;
    protected Button btnDetalhes;

    public CardParte() {
        Design.read(this);
    }
}
