package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CardPedidoTimeline extends VerticalLayout {
    protected HorizontalLayout cardTimeline;
    protected Label dataLabel;
    protected Label statusLabel;
    protected Label remetenteLabel;
    protected TextArea mensagemText;
    protected Button btnVisualizarAnexo;
    protected Button btnBaixarAnexo;

    public CardPedidoTimeline() {
        Design.read(this);
    }
}
