package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CardLinhaTempo extends VerticalLayout {
    protected VerticalLayout cardTimeline;
    protected Label dia;
    protected Label escrevente;
    protected HorizontalLayout cardTimeline21144;
    protected CssLayout barraLateral;
    protected Label registro;
    protected Label dataRegistro;
    protected Label natureza;
    protected Button btnVerRegistro;
    protected TextArea situacaoAtual;

    public CardLinhaTempo() {
        Design.read(this);
    }
}
