package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CartorioParceiro extends VerticalLayout {
    protected VerticalLayout panelAddCartorio;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Estado> estado;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cidade> cidade;
    protected ComboBox<br.com.exmart.rtdpjlite.model.CartorioParceiro> comboCartorioParceiro;
    protected HorizontalLayout panelSelecioarCartorioParceiro;
    protected Button btnConvidarCartorio;
    protected Button btnAddCartorio;
    protected VerticalLayout panelConvidarCartorio;
    protected TextField nomeCartorio;
    protected TextField aliasCartorio;
    protected TextField emailCartorio;
    protected CheckBox ckRecebeEletronico;
    protected Button btnEnviarConvite;
    protected Grid<br.com.exmart.rtdpjlite.model.ProtocoloCartorioParceiro> gridCartorioParceiro;

    public CartorioParceiro() {
        Design.read(this);
    }
}
