package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Intimacao extends VerticalLayout {
    protected VerticalLayout panelCertidao;
    protected RichTextArea textoNotaDevolucao;
    protected VerticalLayout panelIntimacao;
    protected TextArea resultadoIntimacao;
    protected DateTimeField dataHoraIntimacao;
    protected ComboBox<String> statusIntimacao;
    protected Button btnAddResultado;
    protected Grid<br.com.exmart.rtdpjlite.model.IntimacaoProtocolo> gridIntimacao;
    protected HorizontalLayout panelInfo;
    protected Label labelPrimeiraIntimacao;
    protected Label labelValidadePrenotacao;
    protected Button btnAbrirCertidao;
    protected Button btnGerarCertidao;
    protected HorizontalLayout panelEditarProtocolo;
    protected Button btnImprimir;
    protected Button btnCancelar;
    protected Button btnSalvar;
    protected Button btnEditar;

    public Intimacao() {
		Design.read(this);
	}
}
