package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TabSheet;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModalRetroativo extends VerticalLayout {
    protected HorizontalLayout splitPdf;
    protected HorizontalLayout panelPdf;
    protected TabSheet tabSheet;
    protected VerticalLayout panelRegistro;
    protected VerticalLayout formAddInfo11;
    protected ComboBox<String> especialidade;
    protected TextField numReg;
    protected TextField dataReg;
    protected TextField regAnterior;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Natureza> natureza;
    protected ComboBox<br.com.exmart.rtdpjlite.model.SubNatureza> subnatureza;
    protected ComboBox<String> fieldTipoAto;
    protected ComboBox<String> fieldSubTipoAto;
    protected VerticalLayout panelTitulo;
    protected HorizontalLayout panelBotaoUpload;
    protected HorizontalLayout panelMostrarTitulo;
    protected VerticalLayout panelPartes;
    protected VerticalSplitPanel v1;
    protected VerticalLayout panelAddParte1;
    protected VerticalLayout panelPartesForm;
    protected FormLayout formAddParte1;
    protected TextField documento;
    protected TextField nome;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> qualidade;
    protected ComboBox<br.com.exmart.rtdpjlite.model.TipoDocumento> tipoDocumento;
    protected TextField rg;
    protected TextField orgaoExpedidor;
    protected TextField telefone;
    protected TextField email;
    protected FormLayout formAddInfo1;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Nacionalidade> nacionalidade;
    protected ComboBox<br.com.exmart.rtdpjlite.model.EstadoCivil> estadoCivil;
    protected ComboBox<br.com.exmart.rtdpjlite.model.RegimeBens> regimeBens;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Profissao> profissao;
    protected TextField cotas;
    protected FormLayout formAddEndereco1;
    protected TextField cep;
    protected TextField endereco;
    protected TextField nrEndereco;
    protected TextField complemento;
    protected TextField bairro;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Estado> estado;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cidade> cidade;
    protected Button btnNovaParte;
    protected Button btnSalvarParte;
    protected Grid<br.com.exmart.rtdpjlite.model.IndicadorPessoal> gridIndicadorPessoal;
    protected VerticalLayout panelObjetos;
    protected VerticalLayout panelAddObjeto;
    protected Button btnCancelar;
    protected Button btnSalvar;

    public ModalRetroativo() {
        Design.read(this);
    }
}
