package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModalProtocolarLote extends VerticalLayout {
    protected Label txtTipoImportacao;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cliente> comboCliente;
    protected HorizontalLayout panelUpload;
    protected Button btnProcessarArquivo;
    protected Button btnCancelar;

    public ModalProtocolarLote() {
        Design.read(this);
    }
}
