package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModalRegistro extends VerticalLayout {
    protected HorizontalLayout splitRegistro;
    protected VerticalLayout panelTexto;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Modelo> comboTexto;
    protected RichTextArea editoTexto;
    protected Button btnCancelarTexto;
    protected Button btnGerarTexto;
    protected VerticalLayout panelEtiqueta;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Modelo> comboEtiquetas;
    protected RichTextArea editorEtiquetas;
    protected Button btnCancelarEtiqueta;
    protected Button btnAtualizarEtiqueta;
    protected VerticalLayout panelImagem;
    protected HorizontalLayout pdfViewerPanel;
    protected Button btnEditarTexto;
    protected Button btnEditarCarimbo;
    protected Button btnConfirmarRegistro;

    public ModalRegistro() {
        Design.read(this);
    }
}
