package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Upload;
import com.vaadin.ui.HorizontalLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModalReentrada extends VerticalLayout {
    protected VerticalLayout panelApresentante;
    protected TextField apresentante;
    protected TextField apresentanteTelefone;
    protected TextField apresentanteEmail;
    protected VerticalLayout panelSuscitacao;
    protected HorizontalLayout botoesSuscitacao;
    protected Button btnProcedente;
    protected Upload btnAnexarResultado;
    protected Button btnImprocedente;
    protected TextArea observacao;
    protected Button btnCancelar;
    protected Button btnConfirmar;

    public ModalReentrada() {
		Design.read(this);
	}
}
