package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModalNovaMensagem extends VerticalLayout {
    protected VerticalLayout panelMensagem;
    protected ComboBox<br.com.exmart.rtdpjlite.vo.balcaoonline.PedidoMensagemTipo> tipoMensagem;
    protected TextArea mensagem;
    protected Button btnCancelar;
    protected Button btnEnviar;

    public ModalNovaMensagem() {
        Design.read(this);
    }
}
