package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.ComboBox;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Objetos extends VerticalLayout {
    protected VerticalLayout panelObjetos;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Objeto> objetos;
    protected Button btnAdicionarObjeto;
    protected VerticalLayout panelObjetosList;

    public Objetos() {
		Design.read(this);
	}
}
