package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Partes extends VerticalLayout {
    protected VerticalLayout panelAddParte;
    protected VerticalLayout panelParte;
    protected TextField fieldDocumento;
    protected TextField fieldNomeParte;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> fieldQualidadeParte;
    protected HorizontalLayout panelDocumento;
    protected ComboBox<br.com.exmart.rtdpjlite.model.TipoDocumento> fieldTipoDoc;
    protected TextField fieldIdentidade;
    protected TextField fieldOrgaoExp;
    protected TextField fieldDtEmissaoDocumento;
    protected HorizontalLayout panelAddInfo;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Nacionalidade> fieldNacionalidade;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Profissao> fieldProfissao;
    protected HorizontalLayout panelAddInfo2;
    protected ComboBox<br.com.exmart.rtdpjlite.model.EstadoCivil> fieldEstadoCivilParte;
    protected ComboBox<br.com.exmart.rtdpjlite.model.RegimeBens> fieldRegimeBens;
    protected TextField fieldTelefoneParte;
    protected TextField fieldEmailParte;
    protected Button btnAdicionarParte;
    protected VerticalLayout panelAddEndereco;
    protected TextField fieldCepParte;
    protected ComboBox<br.com.exmart.rtdpjlite.model.TipoLogradouro> fieldTipoLogradouro;
    protected TextField fieldEnderecoParte;
    protected TextField fieldNumeroParte;
    protected TextField fieldComplementoParte;
    protected TextField fieldBairroParte;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Estado> fieldUfParte;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cidade> fieldCidadeParte;
    protected Button btnCadastrarConjuge;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> fieldObjeto;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> fieldQualidadeParteold;
    protected TextField fieldCotasParte;
    protected Button btnAddRemoveAtributo;
    protected VerticalLayout conjugePanel;
    protected HorizontalLayout panelAddInfo21;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> fieldConjugeQualidade;
    protected TextField fieldConjugeDocumento;
    protected TextField fieldConjugeNome;
    protected ComboBox<br.com.exmart.rtdpjlite.model.TipoDocumento> fieldConjugeTipoDoc;
    protected TextField fieldConjugeIdentidade;
    protected TextField fieldConjugeOrgaoExp;
    protected TextField fieldConjugeDataDoc;
    protected HorizontalLayout panelAddInfo1;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Nacionalidade> fieldConjugeNacionalidade;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Profissao> fieldConjugeProfissao;
    protected Button btnCopiarDados;
    protected TextField fieldConjugeTelefone;
    protected TextField fieldConjugeEmail;
    protected Button btnAdicionarParte2;
    protected VerticalLayout panelAddEndereco1;
    protected TextField fieldConjugeCep;
    protected ComboBox<br.com.exmart.rtdpjlite.model.TipoLogradouro> fieldConjugeTipoLogradouro;
    protected TextField fieldConjugeEndereco;
    protected TextField fieldConjugeNumero;
    protected TextField fieldConjugeComplemento;
    protected TextField fieldConjugeBairro;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Estado> fieldConjugeUf;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cidade> fieldConjugeCidade;
    protected Button btnAdicionarParte11;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> fieldObjeto1;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Qualidade> fieldConjugeQualidadeOld;
    protected TextField fieldConjugeCota;
    protected Button btnAddRemoveAtributo1;
    protected Button btnAddParte;
    protected Button btnCancelarParte;
    protected Grid<br.com.exmart.rtdpjlite.model.ParteProtocolo> gridPartes;

    public Partes() {
		Design.read(this);
	}
}
