package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Protocolo extends VerticalLayout {
    protected VerticalLayout panelAdd;
    protected HorizontalLayout panelRegistrado;
    protected Button btnReverterRegistro;
    protected HorizontalLayout panelViewRegistro;
    protected Label lblRegistrado;
    protected Label panelRegistrado_nrRegistro;
    protected Label panelRegistrado_dtRegistro;
    protected HorizontalLayout panelNotificacao;
    protected Label panelNotificacao_mensagem;
    protected Label panelNotificacao_ate;
    protected Label panelNotificacao_dtVencNotificacao;
    protected Button panelRegistrado_btnVerRegistro;
    protected Button panelRegistrado_btnVerCertidaoIntimacao;
    protected Button panelRegistrado_btnEntregue;
    protected HorizontalLayout panelDevolvido;
    protected HorizontalLayout panelViewRegistro1;
    protected Label panelDevolvido_dtDevolvido;
    protected Button panelDevolvido_btnVerDevolucao;
    protected Button panelDevolvido_btnEntregue;
    protected Button panelDevolvido_btnReentrada;
    protected HorizontalLayout panelExaminado;
    protected Label labelExaminado;
    protected Label panelExaminado_dtExaminado;
    protected Button panelExaminado_btnVerExame;
    protected Button panelExaminado_btnEntregue;
    protected Button panelExaminado_btnProtocolar;
    protected HorizontalLayout panelCertidaoEmitida;
    protected Button btnReverterCertidao;
    protected HorizontalLayout panelViewRegistro111;
    protected Label panelCertidaoEmitida_dtEmissao;
    protected Button panelCertidaoEmitida_btnVerCertidao;
    protected Button panelCertidaoEmitida_btnEntregueCertidao;
    protected VerticalLayout panelAddProtocolo;
    protected HorizontalLayout panelNatureza1;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Natureza> naturezaTitulo;
    protected ComboBox<br.com.exmart.rtdpjlite.model.SubNatureza> subNaturezaTitulo;
    protected HorizontalLayout panelNatureza;
    protected TextField numeroVias;
    protected TextField valorDocumento;
    protected TextField dtDocumento;
    protected TextField nrContrato;
    protected VerticalLayout panelGuardaConservacao;
    protected CheckBox checkGuarda;
    protected CheckBox checkSigilo;
    protected TextField docParte;
    protected TextField parte;
    protected HorizontalLayout panelRegistro;
    protected TextField numeroReg;
    protected TextField pastaPj;
    protected ComboBox<br.com.exmart.rtdpjlite.model.FormaEntrega> entrega;
    protected CheckBox ckRegistrarOutraPraca;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Usuario> escrevente;
    protected VerticalLayout panelAddApresentante;
    protected ComboBox<br.com.exmart.rtdpjlite.model.Cliente> comboCliente;
    protected ComboBox<br.com.exmart.rtdpjlite.model.portal.UsuarioPortal> comboResponsavel;
    protected TextField apresentante;
    protected TextField responsavel;
    protected TextField apresentanteIdentidade;
    protected TextField apresentanteTelefone;
    protected TextField apresentanteEmail;
    protected TextArea observacao;
    protected VerticalLayout panelAddDatasPrenotacao;
    protected DateField dataPrevista;
    protected DateField dataVencimento;
    protected DateField dataEntrega;
    protected VerticalLayout panelAddDatasExame;
    protected DateField dataExame;
    protected DateField dataRetirada;
    protected VerticalLayout panelView;
    protected VerticalLayout panelViewDatas;
    protected VerticalLayout panelViewProtocolo;
    protected VerticalLayout panelViewApresentante;

    public Protocolo() {
		Design.read(this);
	}
}
