package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.TextField;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Recebimento extends VerticalLayout {
    protected VerticalLayout panelAddRecebimento;
    protected VerticalLayout panelRecebimento;
    protected HorizontalLayout panelFormaRecebimentoDevolucao;
    protected ComboBox<br.com.exmart.rtdpjlite.model.FormaPagamento> comboFormaRecebimento;
    protected TextField valor;
    protected Button btnAdicionarRecebimento;
    protected Button btnAdicionarDevolucao;
    protected Grid<br.com.exmart.rtdpjlite.vo.financeiro.PagamentoProtocoloFinanceiro> gridRecebimentos;
    protected Label labelTotalRecebimentos;
    protected Label labelTotalDevolucoes;
    protected Label labelTotalServicos;
    protected Label labelTotalReceberDevolver;
    protected Label labelTotalReceberDevolverValor;
    protected Button btnAtualizarPagamentosFinanceiro;

    public Recebimento() {
		Design.read(this);
	}
}
