package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registro extends VerticalLayout {
    protected VerticalLayout papel;
    protected VerticalLayout panelExame1;
    protected VerticalLayout panelSituacaoAtual;
    protected TextArea situacaoAtualRegistro;
    protected TextArea observacaoRegistro;
    protected HorizontalLayout v2;
    protected VerticalLayout panelTimeline11;
    protected VerticalLayout panelChecklist;
    protected VerticalLayout panelTimeline1;
    protected VerticalLayout timeline;
    protected Button btnRegistrar;
    protected Button btnDevolver;

    public Registro() {
        Design.read(this);
    }
}
