package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.TextField;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Servicos extends VerticalLayout {
    protected VerticalLayout panelServico;
    protected HorizontalLayout panelValor;
    protected ComboBox<br.com.exmart.rtdpjlite.vo.financeiro.ServicoFinanceiro> servico;
    protected ComboBox<br.com.exmart.rtdpjlite.vo.financeiro.FormaCalculoFinanceiro> formaCalculo;
    protected TextField valorBase;
    protected TextField repeticoes;
    protected Button btnAdicionarServico;
    protected Grid<br.com.exmart.indicadorRTDPJ.ui.vo.ServicosAgrupadoVO> gridServicos;
    protected TextField vlDepositoPrevio;
    protected Label labelTotalServicos;
    protected Label labelTotalServicosValor;
    protected Button btnDetalhesCustas;
    protected Label labelTotalReceberDevolver;
    protected Label labelTotalReceberDevolverValor;
    protected Button btnVerMovimentacoes;
    protected Label labelResultadoCalculo;
    protected Label labelResultadoCalculoValor;
    protected Button btnAtualizarPagamentos;

    public Servicos() {
		Design.read(this);
	}
}
