package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.AbsoluteLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TabMenu extends AbsoluteLayout {
    protected CssLayout menuGde;
    protected Button menuButton;
    protected CssLayout menu;
    protected Button btnRecepcao;
    protected Button btnProtocolos;
    protected Button btnIndicadores;
    protected Button btnLivros;
    protected TabSheet tabMenu;
    protected Accordion accordionTD;
    protected CssLayout menuInicioTD;
    protected Button btnDashboardTD;
    protected Button btnBalcaoTD;
    protected CssLayout menuBuscarTD;
    protected Button btnBuscarPedidosTD;
    protected Button btnBuscarProtocolosTD;
    protected Button btnBuscarIndicadoresTD;
    protected Button btnBuscarLivrosTD;
    protected CssLayout menuProtocolarTD;
    protected Button btnNotificacaoTD;
    protected Button btnExameTD;
    protected Button btnPrenotacaoTD;
    protected Button btnCertidaoTD;
    protected CssLayout menuConfigurarTD;
    protected Button btnConfigTD;
    protected Button btnIntegracoesTD;
    protected Button btnAdminTD;
    protected Accordion accordionPJ;
    protected CssLayout menuInicioPJ;
    protected Button btnDashboardPJ;
    protected Button btnBalcaoPJ;
    protected CssLayout menuBuscarPJ;
    protected Button btnBuscarPedidosPJ;
    protected Button btnBuscarProtocolosPJ;
    protected Button btnBuscarIndicadoresPJ;
    protected Button btnBuscarLivrosPJ;
    protected CssLayout menuProtocolarPJ;
    protected Button btnExamePJ;
    protected Button btnPrenotacaoPJ;
    protected Button btnCertidaoPJ;
    protected CssLayout menuConfigurarPJ;
    protected Button btnConfigPJ;
    protected Button btnIntegracoesPJ;
    protected Button btnAdminPJ;

    public TabMenu() {
        Design.read(this);
    }
}
