package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Grid;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ViewRegistro extends VerticalLayout {
    protected VerticalLayout panelCabecalho;
    protected Label labelTituloProtocolo;
    protected Label labelNumeroProtocolo;
    protected Label labelDataProtocolo;
    protected Button btnDownloadP7s;
    protected TabSheet tabSheetDetalhesRegistro;
    protected VerticalLayout panelDetalhes;
    protected CssLayout panelDetalheRegistro;
    protected Label registroLabel;
    protected Label registroAnteriorLabel;
    protected Label protocoloLabel;
    protected Label naturezaLabel;
    protected Label subnaturezaLabel;
    protected Label tipoAtoLabel;
    protected Label subTipoAtoLabel;
    protected VerticalLayout partesList;
    protected VerticalLayout panelPartes;
    protected VerticalLayout objetosListPanel;
    protected VerticalLayout panelObjetos;
    protected VerticalLayout assinaturasList;
    protected Grid<br.com.exmart.rtdpjlite.vo.AssinaturaDocumentoVO> gridAssinaturas;
    protected TextArea txtSituacaoAtual;
    protected TextArea txtObservacao;
    protected VerticalLayout panelTimeline;
    protected HorizontalLayout pdfViewerPanel;
    protected Button btnEditarRetroativo;
    protected Button btnEmitirCertidao;
    protected Button btnNovaAverbacao;

    public ViewRegistro() {
        Design.read(this);
    }
}
