package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ViewIndicador extends VerticalLayout {
    protected VerticalLayout panelCabecalho;
    protected Label labelTituloProtocolo;
    protected Label labelNumeroProtocolo;
    protected Label labelDataProtocolo;
    protected Label labelDataProtocolo1;
    protected VerticalLayout panelTimeline;
    protected VerticalLayout cardTimeline;
    protected HorizontalLayout cardTimeline21144;

    public ViewIndicador() {
        Design.read(this);
    }
}
