package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ViewIndisponibilidade extends VerticalLayout {
    protected HorizontalLayout panelUpload;
    protected HorizontalLayout panelLoading;
    protected TabSheet tabSheet;
    protected Grid<br.com.exmart.rtdpjlite.vo.indisponibilidade.ParteIndisponivel> gridEncontrados;
    protected Grid<br.com.exmart.rtdpjlite.vo.indisponibilidade.ParteIndisponivel> gridValidar;
    protected Grid<br.com.exmart.rtdpjlite.vo.indisponibilidade.ParteIndisponivel> gridNaoEncontrados;
    protected Grid<br.com.exmart.rtdpjlite.vo.indisponibilidade.ParteIndisponivelRegistro> gridRegistros;

    public ViewIndisponibilidade() {
        Design.read(this);
    }
}
