package br.com.exmart.indicadorRTDPJ.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VisualizarImagens extends VerticalLayout {
    protected Label labelTituloProtocolo;
    protected VerticalLayout pdfViewer;
    protected Image thumbDoc;
    protected VerticalLayout v1;
    protected VerticalLayout panelExame;
    protected Button btnRegistrar;
    protected Button btnDevolver;
    protected VerticalLayout panelTimeline;
    protected VerticalLayout cardTimelineV2114;
    protected HorizontalLayout cardTimeline2114;
    protected VerticalLayout cardTimelineV21141;
    protected HorizontalLayout cardTimeline21141;
    protected VerticalLayout cardTimelineV21142;
    protected HorizontalLayout cardTimeline21142;
    protected VerticalLayout cardTimelineV21143;
    protected HorizontalLayout cardTimeline21143;
    protected VerticalSplitPanel panelPartes1;
    protected VerticalLayout panelAddParte1;
    protected FormLayout formAddParte1;
    protected TextField fieldCpfCnpjParte2;
    protected TextField fieldNomeParte1;
    protected TextField fieldCpfCnpjParte11;
    protected TextField fieldTelefoneParte1;
    protected ComboBox<String> fieldQualidadeParte1;
    protected TextField fieldEmailParte1;
    protected FormLayout formAddInfo1;
    protected ComboBox<String> fieldEstadoCivilParte11;
    protected ComboBox<String> fieldEstadoCivilParte2;
    protected TextField fieldProfissaoParte1;
    protected TextField fieldValorParticipacaoParte1;
    protected TextField fieldCotasParte1;
    protected FormLayout formAddEndereco1;
    protected TextField fieldCepParte1;
    protected TextField fieldEnderecoParte1;
    protected TextField fieldNumeroParte1;
    protected TextField fieldComplementoParte1;
    protected TextField fieldBairroParte1;
    protected ComboBox<String> fieldCidadeParte1;
    protected ComboBox<String> fieldUfParte1;
    protected Button btnAdicionarParte1;
    protected Grid gridPartes1;
    protected VerticalSplitPanel panelObjetos;
    protected VerticalLayout panelAddObjeto1;
    protected Button btnAdicionarObjeto1;
    protected Grid gridObjetos1;

    public VisualizarImagens() {
		Design.read(this);
	}
}
