UPDATE status set bloquear_protocolo = true
		WHERE nome IN ('DEVOLVIDO','REGISTRADO','PRONTO PARA ENTREGA','ENTREGUE','CANCEL. PELA PARTE','CANCEL. JUDICIALMENTE','CANCEL. DECURSO DE PRAZO',
		'SUSCITAÇÃO DE DÚVIDA', 'APTO PARA REGISTRO','INFORMADO PORTAL - REGISTRO','INFORMADO PORTAL - ENCAMINHAR CERTIDÃO','CERTIDÃO INTIMAÇÃO EMITIDA')
