insert into natureza (natureza_tipo_id, nome) values(1,'ABAIXO ASSINADO');
insert into natureza (natureza_tipo_id, nome) values(1,'ABERTURA DE CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'ABERTURA FILIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ACAO DE INDENIZACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ACORDO');
insert into natureza (natureza_tipo_id, nome) values(1,'ACORDO DE CREDITO COMPRADOR');
insert into natureza (natureza_tipo_id, nome) values(1,'ADENDO');
insert into natureza (natureza_tipo_id, nome) values(1,'ADENDO A ATA');
insert into natureza (natureza_tipo_id, nome) values(1,'ADESAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ADITAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ADITIVO');
insert into natureza (natureza_tipo_id, nome) values(1,'ADMIMINISTRACAO CANTINA');
insert into natureza (natureza_tipo_id, nome) values(1,'ADMINISTRACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'AGENCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'AGENCIAMENTO FIDUCIARIO');
insert into natureza (natureza_tipo_id, nome) values(1,'AGENDA SAUDE & AGENDA HOSPITAL');
insert into natureza (natureza_tipo_id, nome) values(1,'AGREGAMENTO DE VEICULO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALIENACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALIENACAO FIDUCIARIA');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT FIRMA INDIVIDUAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT OBJETIVO SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. CT. IMPORTACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. DE PERIODICO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. DEN. SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. ENDERECO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. ESTATUTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. FUNDO INVESTIMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT. P/ ESTE OFICIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ALT.DE CONTR.SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ALTERACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALTERACAO D0 REGULAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALTERACAO DE CONTRATO');
insert into natureza (natureza_tipo_id, nome) values(1,'ALTERACAO MATRICULA DE JORNAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ALTEROU P/ JUCESP');
insert into natureza (natureza_tipo_id, nome) values(1,'ALVARA');
insert into natureza (natureza_tipo_id, nome) values(1,'ANEXO');
insert into natureza (natureza_tipo_id, nome) values(1,'ANULACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'APOLICE');
insert into natureza (natureza_tipo_id, nome) values(1,'APOSTILA');
insert into natureza (natureza_tipo_id, nome) values(1,'APRESENTAÇÃO');
insert into natureza (natureza_tipo_id, nome) values(1,'AQUISICAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ARQUIVAMENTO ESTATUTOS SOCIAIS');
insert into natureza (natureza_tipo_id, nome) values(1,'ARRENDAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ARRENDAMENTO DE VEICULO');
insert into natureza (natureza_tipo_id, nome) values(1,'ARRENDAMENTO ESTAB.COML.');
insert into natureza (natureza_tipo_id, nome) values(1,'ARRENDAMENTO MERCANTIL');
insert into natureza (natureza_tipo_id, nome) values(1,'ASSUNCAO OBRIGACOES');
insert into natureza (natureza_tipo_id, nome) values(1,'ASSUNCAO RESPONSABILIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA ALT DE REGULAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA ASS GRL');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA ASS GRL-TRANSFERENCIA');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA AUTENTICACAO DE ASSINATURA');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA DE EXONERACAO DE CARGO');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA DE POSSE');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA DE RETIFICACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA DE REUNIAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA DISSOLUCAO ENTIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA ELEICAO DIRETORIA');
insert into natureza (natureza_tipo_id, nome) values(1,'ATA NOTARIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ATESTADO');
insert into natureza (natureza_tipo_id, nome) values(1,'ATESTADO DE DOMICILIO');
insert into natureza (natureza_tipo_id, nome) values(1,'ATESTADO DE ESTADO CIVIL');
insert into natureza (natureza_tipo_id, nome) values(1,'AUTO INFRACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'AUTORIZACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'AUTORIZACAO DEP ZELADORIA');
insert into natureza (natureza_tipo_id, nome) values(1,'AVERBACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'BAIXA');
insert into natureza (natureza_tipo_id, nome) values(1,'BAIXA CED. CRED. INDL.');
insert into natureza (natureza_tipo_id, nome) values(1,'BAIXA DE CONTRATO');
insert into natureza (natureza_tipo_id, nome) values(1,'BALANCO');
insert into natureza (natureza_tipo_id, nome) values(1,'BOLETIM');
insert into natureza (natureza_tipo_id, nome) values(1,'BOLETIN OCORRENCIA');
insert into natureza (natureza_tipo_id, nome) values(1,'BORDERO DE CHEQUE');
insert into natureza (natureza_tipo_id, nome) values(1,'BREVE RELATO');
insert into natureza (natureza_tipo_id, nome) values(1,'BUSCA');
insert into natureza (natureza_tipo_id, nome) values(1,'CANCELADO POR ERRO NO SISTEMA');
insert into natureza (natureza_tipo_id, nome) values(1,'CANCELAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CANCELAMENTO DE INDISPONILIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'CAPITAL DE GIRO');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTA');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTA DE ANUENCIA');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTA DE FIANCA');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTA DE INSENCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTA DE RETRATACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTAO POSTAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTAO PROPOSTA DE SEGURO VIDA');
insert into natureza (natureza_tipo_id, nome) values(1,'CARTEIRA PROFISSIONAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CAUCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CEDULA CRED BANCARIO');
insert into natureza (natureza_tipo_id, nome) values(1,'CEDULA CREDITO COMERCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CEDULA CREDITO INDUSTRIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CEDULA DE CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'CEDULA RURAL PIGNORATICIA');
insert into natureza (natureza_tipo_id, nome) values(2,'CERTIDAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CESSAO CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'CESSAO DE DIREITOS');
insert into natureza (natureza_tipo_id, nome) values(1,'CESSAO DE USO TELEFONE');
insert into natureza (natureza_tipo_id, nome) values(1,'CESSAO/TRANSFERENCIA');
insert into natureza (natureza_tipo_id, nome) values(1,'CHANCELA MECANICA');
insert into natureza (natureza_tipo_id, nome) values(1,'CHAPA');
insert into natureza (natureza_tipo_id, nome) values(1,'CHEQUE');
insert into natureza (natureza_tipo_id, nome) values(1,'CIRCULAR');
insert into natureza (natureza_tipo_id, nome) values(1,'CODIGOS FONTES');
insert into natureza (natureza_tipo_id, nome) values(1,'COLETANIA');
insert into natureza (natureza_tipo_id, nome) values(1,'COMERCIALIZACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'COMISSAO FORMATURA');
insert into natureza (natureza_tipo_id, nome) values(1,'COMITIVA');
insert into natureza (natureza_tipo_id, nome) values(1,'COMODATO');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPOSICAO AMIGAVEL');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPOSICAO E OBRIG DE FAZER');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPRA E VENDA');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPRA E VENDA VEICULO');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPRA VDA RES DOMINIO');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPRA VENDA ESTABEL COML.');
insert into natureza (natureza_tipo_id, nome) values(1,'COMPROMISSO');
insert into natureza (natureza_tipo_id, nome) values(1,'COMUNICADO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONCESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONCESSAO CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONCORDANCIA DE DOACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONDICOES DE VENDA');
insert into natureza (natureza_tipo_id, nome) values(1,'CONFIRMACAO ESTADO CIVIL');
insert into natureza (natureza_tipo_id, nome) values(1,'CONFISSAO DE DIVIDA');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSOLIDACAO CONTRATO SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSOLIDACAO DO REGULAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONST. DE BANDA');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSTITUICAO CONDOMINIO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSTITUICAO CONSORCIO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSTITUICAO DE GARANTIA');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSTITUICAO DE USUFRUTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSTITUICAO DO FUNDO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONSTRUCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTA PR');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTR. DE FINANCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO ANTE  MARITAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO CREDENCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE AGENCIAMENTO DE SE');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE CESSAO DE DIREITOS');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE DESCONTO TITULOS');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE EMPRESTIMO/FINANC');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE LOCACAO NAO RES');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE MUTUO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO DE PREST DE GARANTIA');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO FINANCIAMENTO MEDIANT');
insert into natureza (natureza_tipo_id, nome) values(1,'CONTRATO PROMESSA CESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONVENCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CONVENIO CONCESSAO FINANCIAM');
insert into natureza (natureza_tipo_id, nome) values(1,'CONVOCACAO DE ASSEMBLEIA');
insert into natureza (natureza_tipo_id, nome) values(1,'COPIA');
insert into natureza (natureza_tipo_id, nome) values(1,'CREDENCIAMENTO ASS TECNICA');
insert into natureza (natureza_tipo_id, nome) values(1,'CREDITO COMERCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CREDITO FINANCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CREDITO ROTATIVO');
insert into natureza (natureza_tipo_id, nome) values(1,'CRIACAO DE PAROQUIA');
insert into natureza (natureza_tipo_id, nome) values(1,'CT PREST DE SERVICO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. DE ADESAO PRODUTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. DESCONTO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. FIN CAPITAL DE GIRO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. INDUSTRIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. P DESCONT DE CH');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. PADRAO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. SERVICOS');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. SIGILO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. TRABALHO');
insert into natureza (natureza_tipo_id, nome) values(1,'CT. TRANSPORTE');
insert into natureza (natureza_tipo_id, nome) values(1,'CT.DE PRESTACAO DE SERVICOS');
insert into natureza (natureza_tipo_id, nome) values(1,'DACAO EM PAGAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'DEBENTURES-CT CAUCAO ACOES');
insert into natureza (natureza_tipo_id, nome) values(1,'DEBENTURES-CT CESSAO CONDIC DR');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO DE CELIBATO');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO DE POSSE');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO DE RESPONSABILIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO DE VONTADE');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO P/ REGISTRO DE OBRA');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO PODEDES');
insert into natureza (natureza_tipo_id, nome) values(1,'DECLARACAO QUITACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'DECRETO');
insert into natureza (natureza_tipo_id, nome) values(1,'DELIBERACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'DEMONSTRATIVO');
insert into natureza (natureza_tipo_id, nome) values(1,'DESENHO');
insert into natureza (natureza_tipo_id, nome) values(1,'DESENHO ARTISTICO');
insert into natureza (natureza_tipo_id, nome) values(1,'DESENQUADRAMENTO DE EPP');
insert into natureza (natureza_tipo_id, nome) values(1,'DESENQUADRAMENTO ME');
insert into natureza (natureza_tipo_id, nome) values(1,'DIPLOMA');
insert into natureza (natureza_tipo_id, nome) values(1,'DISSOLUCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'DISTRATO');
insert into natureza (natureza_tipo_id, nome) values(1,'DISTRATO SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'DOACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'DOCUMENTO DE IDENTIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'DOCUMENTO ESTRANGEIRO');
insert into natureza (natureza_tipo_id, nome) values(1,'DUPLICATA');
insert into natureza (natureza_tipo_id, nome) values(1,'Documento');
insert into natureza (natureza_tipo_id, nome) values(1,'EDITAL CONVOCACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'EDITAL DE PROCLAMAS');
insert into natureza (natureza_tipo_id, nome) values(1,'ELEICAO PARA CIPA');
insert into natureza (natureza_tipo_id, nome) values(1,'EMANCIPACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'EMBLEMA');
insert into natureza (natureza_tipo_id, nome) values(1,'EMPREITADA');
insert into natureza (natureza_tipo_id, nome) values(1,'EMPRESTIMO');
insert into natureza (natureza_tipo_id, nome) values(1,'ENCERRAMENTO DE ATIVIDADES');
insert into natureza (natureza_tipo_id, nome) values(1,'ENCERRAMENTO DE FILIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ENQUADRAMENTO DE EPP');
insert into natureza (natureza_tipo_id, nome) values(1,'ENQUADRAMENTO ME');
insert into natureza (natureza_tipo_id, nome) values(1,'ESCRITURA PART DIR OBRIG');
insert into natureza (natureza_tipo_id, nome) values(1,'ESCRITURA PUB DE PACTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ESCRITURA PUBLICA DECLARATORIA');
insert into natureza (natureza_tipo_id, nome) values(1,'ESCRITURA TESTAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ESTATUTO SOCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'ESTUDO');
insert into natureza (natureza_tipo_id, nome) values(1,'EXECUCAO OBRAS');
insert into natureza (natureza_tipo_id, nome) values(1,'EXONERACAO DE FIANCA');
insert into natureza (natureza_tipo_id, nome) values(1,'EXPLORACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'EXTINCAO ENTIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'EXTRATO CARTAO CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'FA-CLUBE');
insert into natureza (natureza_tipo_id, nome) values(1,'FIANCA');
insert into natureza (natureza_tipo_id, nome) values(1,'FICHA DE SOCIO');
insert into natureza (natureza_tipo_id, nome) values(1,'FICHA INSCRICAO');
insert into natureza (natureza_tipo_id, nome) values(1,'FINANCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'FIRMA INDIVIDUAL');
insert into natureza (natureza_tipo_id, nome) values(1,'FISCALIZACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'FOMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'FOMENTO MERCANTIL');
insert into natureza (natureza_tipo_id, nome) values(1,'FORNECIMENTO DE MERCADORIA');
insert into natureza (natureza_tipo_id, nome) values(1,'FRANQUIA');
insert into natureza (natureza_tipo_id, nome) values(1,'FUNDO COMMODITIES');
insert into natureza (natureza_tipo_id, nome) values(1,'FUNDO INVESTIMENTO RENDA FIXA');
insert into natureza (natureza_tipo_id, nome) values(1,'GARANTIA');
insert into natureza (natureza_tipo_id, nome) values(1,'GESTAO UNIAO E ACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'HISTORICO ESCOLAR');
insert into natureza (natureza_tipo_id, nome) values(1,'IDENTIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'IMPORTACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'INCORPORACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'INDICE');
insert into natureza (natureza_tipo_id, nome) values(1,'INDISPONIBILIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'INFORMACAO PRESTADA');
insert into natureza (natureza_tipo_id, nome) values(1,'INST. USUFRUTO');
insert into natureza (natureza_tipo_id, nome) values(1,'INST.PART.IMISSAO DE POSSE');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR P VDA COMPRA ACOES');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PART 2¦ ALTERACAO REGULA');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PART CONTR CESSAO E AQUI');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PART CONVALESCIMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PART DE CESSAO E TRANSF');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PART RENEG OP CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PARTIC CESSAO DE CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PARTIC CONFISSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PARTIC CONTR SUBSCRICAO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR PARTIC DE CONFIS E PARC');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR. PART REFORCO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTR. PART RENEGOCIACAO OP CR');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTRUMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'INSTRUMENTO PARTICULAR');
insert into natureza (natureza_tipo_id, nome) values(1,'INTEIRO TEOR');
insert into natureza (natureza_tipo_id, nome) values(1,'INTERRUPCAO SERVICO');
insert into natureza (natureza_tipo_id, nome) values(1,'INVESTIMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'IPVA');
insert into natureza (natureza_tipo_id, nome) values(1,'JORNAL');
insert into natureza (natureza_tipo_id, nome) values(1,'LAUDO');
insert into natureza (natureza_tipo_id, nome) values(1,'LETRA CAMBIO');
insert into natureza (natureza_tipo_id, nome) values(1,'LETRA MUSICA');
insert into natureza (natureza_tipo_id, nome) values(1,'LICENCA CERTIFICADO');
insert into natureza (natureza_tipo_id, nome) values(1,'LISTA DE PRESENCA');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO 01-VOLUME I A VI');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO ATAS 01');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO ATAS 02');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO ATAS 03');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO ATAS 04');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO CAIXA');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 01');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 02');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 03');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 04');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 05');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 06');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 07');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 08');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 09');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 10');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 11');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 12');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 13');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 14');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 15');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 16');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 17');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 18');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 19');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 20');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 21');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 22');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 23');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 24');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 25');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 26');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 27');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 28');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 29');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 30');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 31');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 32');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 33');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 34');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 35');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 36');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 37');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 38');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 39');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO 40');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 41');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 42');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 43');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 44');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 45');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 46');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 47');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 48');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 49');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 50');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 51');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 52');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 53');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 54');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 55');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 56');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 57');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 58');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 59');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 60');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 61');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 62');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 63');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 64');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO DIARIO GERAL 65');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO FINANC 01');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO RAZAO');
insert into natureza (natureza_tipo_id, nome) values(1,'LIVRO RAZAO 02');
insert into natureza (natureza_tipo_id, nome) values(1,'LOCACAO DE BENS');
insert into natureza (natureza_tipo_id, nome) values(1,'LOCACAO DE EMPILHADEIRAS');
insert into natureza (natureza_tipo_id, nome) values(1,'LOCACAO DE SERVICOS');
insert into natureza (natureza_tipo_id, nome) values(1,'LOCACAO DE VEICULOS');
insert into natureza (natureza_tipo_id, nome) values(1,'LOCACAO EQUIPAMENT INDUSTRIALL');
insert into natureza (natureza_tipo_id, nome) values(1,'LOCACAO IMOVEL');
insert into natureza (natureza_tipo_id, nome) values(1,'MANDADO');
insert into natureza (natureza_tipo_id, nome) values(1,'MANDATO DE CANCELAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'MAO DE OBRA');
insert into natureza (natureza_tipo_id, nome) values(1,'MATRICULA');
insert into natureza (natureza_tipo_id, nome) values(1,'MATRICULA DE JORNAL');
insert into natureza (natureza_tipo_id, nome) values(1,'MATRICULA DO PERIODICO');
insert into natureza (natureza_tipo_id, nome) values(1,'MEDICAO DE LINHA-TRANSPORTES-');
insert into natureza (natureza_tipo_id, nome) values(1,'MEMORANDO');
insert into natureza (natureza_tipo_id, nome) values(1,'MEMORIAL DESCRITIVO');
insert into natureza (natureza_tipo_id, nome) values(1,'MIN CONTR ABER C VINC EMPRES');
insert into natureza (natureza_tipo_id, nome) values(1,'MODELO');
insert into natureza (natureza_tipo_id, nome) values(1,'MUTUO');
insert into natureza (natureza_tipo_id, nome) values(1,'NOME DE BANDA');
insert into natureza (natureza_tipo_id, nome) values(1,'NOMEACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTA DE CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTA FISCAL');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTA PROMISSORIA');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTICIA');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTIFICACAO DISP ENTR');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTIFICACAO EXTRAJUDICIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'NOTIFICACAO POR A.R.');
insert into natureza (natureza_tipo_id, nome) values(1,'OBRIGACOES');
insert into natureza (natureza_tipo_id, nome) values(1,'OFICIO');
insert into natureza (natureza_tipo_id, nome) values(1,'OPCAO DE COMPRA/VENDA');
insert into natureza (natureza_tipo_id, nome) values(1,'OPERACAO DE CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'ORACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ORCAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'ORDEM DE SERVICO');
insert into natureza (natureza_tipo_id, nome) values(1,'ORDEM TRANSF QUOTAS ESCRIT');
insert into natureza (natureza_tipo_id, nome) values(1,'PAGINA DE SITE');
insert into natureza (natureza_tipo_id, nome) values(1,'PARCELAMENTO DE DIVIDA');
insert into natureza (natureza_tipo_id, nome) values(1,'PASSAPORTE');
insert into natureza (natureza_tipo_id, nome) values(1,'PATROCINIO');
insert into natureza (natureza_tipo_id, nome) values(1,'PEDIDO');
insert into natureza (natureza_tipo_id, nome) values(1,'PENHOR');
insert into natureza (natureza_tipo_id, nome) values(1,'PERMISSAO DE USO');
insert into natureza (natureza_tipo_id, nome) values(1,'PERMUTA');
insert into natureza (natureza_tipo_id, nome) values(1,'PLANEJAMENTO/MARKETING');
insert into natureza (natureza_tipo_id, nome) values(1,'PLANILHA');
insert into natureza (natureza_tipo_id, nome) values(1,'PLANO DE OPERACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'POEMAS E POESIAS');
insert into natureza (natureza_tipo_id, nome) values(1,'PRESTACAO AVAL');
insert into natureza (natureza_tipo_id, nome) values(1,'PRESTACAO DE SERVICOS');
insert into natureza (natureza_tipo_id, nome) values(1,'PRESTACAO GARANTIA');
insert into natureza (natureza_tipo_id, nome) values(1,'PROCESSO / PROCEDIMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROCESSO JUDICIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'PROCURACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROJETO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROMESSA DE CESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROMESSA DE CONCESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROPOSTA');
insert into natureza (natureza_tipo_id, nome) values(1,'PRORROGACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'PRORROGACAO FIANCA');
insert into natureza (natureza_tipo_id, nome) values(1,'PRORROGACAO LOCACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROSPECTO');
insert into natureza (natureza_tipo_id, nome) values(1,'PROTOCOLO DE USO');
insert into natureza (natureza_tipo_id, nome) values(1,'QUITACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'RATIFICACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'RE-RATIFICACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'RE-RATIFICACAO CONTRATO');
insert into natureza (natureza_tipo_id, nome) values(1,'RECIBO');
insert into natureza (natureza_tipo_id, nome) values(1,'RECONHECIMENTO DE FILHO');
insert into natureza (natureza_tipo_id, nome) values(1,'RECONHECIMENTO DIVIDA');
insert into natureza (natureza_tipo_id, nome) values(1,'RECURSOS DO FAT - FUNDO');
insert into natureza (natureza_tipo_id, nome) values(1,'REFINANCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'REFINANCIAMENTO CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'REFORMULACAO ESTATUTOS');
insert into natureza (natureza_tipo_id, nome) values(1,'REG DOC ELETRONICO FINS CONSER');
insert into natureza (natureza_tipo_id, nome) values(1,'REG.PUBLICACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'REGIMENTO INTERNO');
insert into natureza (natureza_tipo_id, nome) values(1,'REGISTRO COMERCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'REGISTRO CPF/CIC');
insert into natureza (natureza_tipo_id, nome) values(1,'REGISTRO DE ARMA DE FOGO');
insert into natureza (natureza_tipo_id, nome) values(1,'REGISTRO DE ESTADO CIVIL');
insert into natureza (natureza_tipo_id, nome) values(1,'REGISTRO JORNAL');
insert into natureza (natureza_tipo_id, nome) values(1,'REGISTRO R.G.');
insert into natureza (natureza_tipo_id, nome) values(1,'REGULAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'RELACAO DE ASSOCIADOS');
insert into natureza (natureza_tipo_id, nome) values(1,'RELACAO DE CONDOMINOS');
insert into natureza (natureza_tipo_id, nome) values(1,'RELACAO DE PASSAROS P/IBAMA');
insert into natureza (natureza_tipo_id, nome) values(1,'RELACAO DE PATRIMONIO');
insert into natureza (natureza_tipo_id, nome) values(1,'RELATORIO');
insert into natureza (natureza_tipo_id, nome) values(1,'RENOVACAO APOLICE');
insert into natureza (natureza_tipo_id, nome) values(1,'RENUNCIA');
insert into natureza (natureza_tipo_id, nome) values(1,'REPASSE');
insert into natureza (natureza_tipo_id, nome) values(1,'REPRESENTACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'REPRESENTACAO COMERCIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'REQUERIMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'RESCISAO CONTRATO DE LOCACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'RESCISAO CONTRATUAL');
insert into natureza (natureza_tipo_id, nome) values(1,'RESERVA CREDITO');
insert into natureza (natureza_tipo_id, nome) values(1,'RESERVA DE DOMINIO');
insert into natureza (natureza_tipo_id, nome) values(1,'RESOLUCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'RETIFICACAO DA ATA DA ASSEMBL');
insert into natureza (natureza_tipo_id, nome) values(1,'RETIFICACAO DO REGULAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'REVISTA (PROPAGANDA)');
insert into natureza (natureza_tipo_id, nome) values(1,'REVOGACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'REVOGACAO PROCURACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'ROTEIRO SINTATICO');
insert into natureza (natureza_tipo_id, nome) values(1,'SEGUNDO FINANCIAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'SEGURO OBRIGATORIO');
insert into natureza (natureza_tipo_id, nome) values(1,'SENTENCA DE DIVORCIO');
insert into natureza (natureza_tipo_id, nome) values(1,'SEPARACAO EXTRAJUDICIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'SIMBOLO');
insert into natureza (natureza_tipo_id, nome) values(1,'SOC. EM CONTA DE PARTICIPACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'SOLICITACAO PREVER EMPRESARIAL');
insert into natureza (natureza_tipo_id, nome) values(1,'SUB-ROGACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'SUBLOCACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'SUBSTABELECIMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'SUBSTABELECIMENTO  PROCURACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'SUBSTITTUICAO DE GARANTIA');
insert into natureza (natureza_tipo_id, nome) values(1,'SUBSTITUICAO DE BENS');
insert into natureza (natureza_tipo_id, nome) values(1,'SUPLEMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'SUPLEMENTO AO REGULAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'SUPLEMENTO DA 1 SERIE');
insert into natureza (natureza_tipo_id, nome) values(1,'TABELA');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO AB.E ENCERRAM.TALONARIO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO COMPROMISSO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO CONTRATUAL');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE ABERTURA');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE ACORDO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE AUTENTICACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE AUTORIZACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE CESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE CONVENIO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE CONVIVENCIA - OBRIGAC');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE OUTORGA');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE PERMISSAO REMUNERADA');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE POSSE');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE RECEBIMENTO E ACEITAC');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE RES CONTR');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO DE SEPARACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO ENCERRAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO ENTREGA DOCUMENTOS');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO LIBERACAO GARANTIA');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO QUITACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO RENEGOCIACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO RESPONSABILIDADE');
insert into natureza (natureza_tipo_id, nome) values(1,'TERMO TRANSFERENCIA');
insert into natureza (natureza_tipo_id, nome) values(1,'TESTAMENTO');
insert into natureza (natureza_tipo_id, nome) values(1,'TRADUCAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TRANFORM DE ME EM EPP');
insert into natureza (natureza_tipo_id, nome) values(1,'TRANSACAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TRANSFERENCIA CESSAO');
insert into natureza (natureza_tipo_id, nome) values(1,'TRANSFORMACAO SC P/ COML.');
insert into natureza (natureza_tipo_id, nome) values(1,'VER LIVRO');
insert into natureza (natureza_tipo_id, nome) values(1,'VISTORIA TECNICA');
insert into natureza (natureza_tipo_id, nome) values(1,'ZELADORIA (OCUPACAO)');
