create table protocolo (
	id serial, 
	numero bigint,
	natureza_id bigint,
	forma_entrega_id bigint,
	tipo_protocolo_id bigint,
	parte_id bigint, 
	status_id bigint, 
	vias integer, 
	valor decimal(12,2),
	data_protocolo date,
	data_doc date,
	data_prevista date,
	data_vencimento date,
	data_entrega TIMESTAMP,
	apresentante_rg varchar(255),
	pasta_pj varchar(255),
	responsavel varchar(255),
	apresentante varchar(255),
	telefone varchar(255),
	email varchar(255),
	observacoes text,
	parte varchar(250) not null,
	registro_referencia varchar(255),
	parte_documento varchar(250) not null,
	objetos jsonb default '{}',
	numero_registro varchar(255),
	observacao_registro TEXT,
	situacao_atual_registro TEXT,
	dt_registro TIMESTAMP,
	nr_exame_calculo_referencia bigint,
	CONSTRAINT pk_protocolo PRIMARY KEY (id)
	);
