INSERT INTO usuario (nome, email, senha) VALUES ('Aline Suellen de Pinho Tavares', 'email1@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Amanda Carreira', 'email2@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Amanda Costa dos Santos', 'email3@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Andréa Cristina Silvestre de Almeida', 'email4@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Bianca Fernandes de Oliveira', 'email5@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Brena Gabrielle de Oliveira Satel', 'email6@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Bruna Barbosa Scorsi', 'email7@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Carla Goulart Graziano de Oliveira', 'email8@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Caroline Silva Teles', 'email9@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Claudia Ferraz dos Santos', 'email10@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Daniela Souza Paes', 'email11@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Debora Galdino Brando Ferrari', 'email12@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Edilma do Nascimento Melo', 'email13@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Evellyn Nascimento dos Santos', 'email14@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Fernanda Miska Garcia', 'email15@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Fernando Gonzaga de Freitas', 'email16@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Katia Maria da Silva Sousa', 'email17@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Katiane da Mota Evangelista', 'email18@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Kauany Santos Menezes', 'email19@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Lucia Helena Ribeiro da Silva', 'email20@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Mariana Monteiro das Neves', 'email21@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Marli Alves dos Santos', 'email22@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Maryana Matos da Silva', 'email23@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Priscila Vieira', 'email24@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Ruy Veridiano Patu Rebello Pinho', 'email25@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Talita Braga Trovo', 'email26@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Tatiane Oliveira da Silva', 'email27@email.com','1234');
INSERT INTO usuario (nome, email, senha) VALUES ('Valeria Feitosa de Souza', 'email28@email.com','1234');
