ALTER TABLE protocolo ALTER COLUMN data_protocolo TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE protocolo ALTER COLUMN data_doc  TYPE DATE;
ALTER TABLE protocolo ALTER COLUMN data_prevista  TYPE DATE;
ALTER TABLE protocolo ALTER COLUMN data_vencimento  TYPE DATE;